### ISSUE TITLE
Creating backup infinitely spins

### ISSUE THREAD

**Issue by Brian11f** [enupal/backup#10]
### Description
After install, I hit the new backup button and nothing updates in the main management menu. The bottom left status indicator "Creating backup" just infinitely spins.

I checked craft error logs but did not see anything that looked relevant. My local exhibited the same behavior.

### Steps to reproduce

1. Installed backup on server via the craft admin user interface.
2. Pressed new backup button.

### Additional info

- Craft version: 3.0.22
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.24
- Plugin version: 1.2.0
- Operating system: Ubuntu 18.04.1 LTS

**Comment by andrelopez** [comment]
Hi @Brian11f 

Could you please click in the link of the backup in the index page? What is the Status in the view page?

Could you please check that `allow_url_fopen` is enabled in your server?

Best,

**Comment by Brian11f** [comment]
Hi @andrelopez,

Thanks for getting back to me! The php configuration has allow_url_fopen set on. The Status view page is blank.

**Comment by Brian11f** [comment]
@andrelopez Sure here is the screenshot.
![screen shot 2018-11-05 at 3 28 00 pm](https://user-images.githubusercontent.com/16297587/48033381-fbcbda00-e10f-11e8-9871-6067805893ae.png)
It just stays static in that state.

**Comment by andrelopez** [comment]
Thanks for following up @Brian11f,

I see the issue now. It looks like a Craft Error. Is there any chance that you can send us an email to support@enupal.com with a zip file of the following files:
- Export just the `queue` table of your database 
- The next log file `storage/logs/queue.log`

Then you can delete all the rows of the `queue` table and try the backup again?

**Comment by andrelopez** [comment]
Hi @Brian11f 

We just released Enupal Backup with improves in the backup process, once you delete all rows in your queue table, please update your plugin to v1.2.1 and let us know if the issue is solved?

Best,

**Comment by Brian11f** [comment]
Hello @andrelopez ,

Thank you so much for the speedy response! Sorry about not getting you the queue.log. v1.2.1 has fixed the issue above.

Thanks!

**Comment by andrelopez** [comment]
No problem @Brian11f. Thank you for reporting this behavior.

Best,
