### ISSUE TITLE
Feature Request: Notification for Failed Backups

### ISSUE THREAD

**Issue by kgrote** [enupal/backup#15]
It would be great to have a setting where the plugin will send an email if the backup fails. Getting an email if the backup is successful is less useful, since you start to ignore it after a while.

**Comment by andrelopez** [comment]
Hi @kgrote 

Thanks for reaching out. Adding twig logic the "Subject" setting to add a proper message would work? e.g

`{% if backup.getStatusName() == 'Finished' %} Backup successful {% else %} Backup Error  {% endif %}`

You can also modify the "Email Recipients" setting or any other using the `EVENT_BEFORE_SEND_NOTIFICATION_EMAIL` fired after a Backup is finished. Please see a full example [here](https://enupal.com/craft-plugins/enupal-backup/docs/development/events)
