### ISSUE TITLE
Backups do not upload to the cloud

### ISSUE THREAD

**Issue by umkasanki** [enupal/backup#18]
### Description
I use your plugin on several sites. But at one of the sites backups are not uploaded to the cloud.
On all sites, I use the same data to connect to the AWS S3.

My log: https://1drv.ms/u/s!AgmGxdO2gZN2gaNJ4sC_leXje_bIUg

### Steps to reproduce

1. Install Enupal Backup
2. Setting up AWS S3.
2. Run backup

### Additional info

- Craft version:  Craft Solo 3.1.12
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23
- Plugin version: 1.2.6

**Comment by andrelopez** [comment]
Hi @umkasanki 

Thanks for reaching out. I have checked your logs and I found the next error:

insufficient_space

However the error is related to Dropbox, this error is due that your dropbox account is out of space you can find more info [here](https://www.dropboxforum.com/t5/API-Support-Feedback/Detecting-Failure-in-App-for-Full-dropbox/m-p/222619/highlight/true#M11916)

I don't see any errors related to AWS.

Best,

**Comment by umkasanki** [comment]
Excuse for troubling. The problem was in my AWS S3
