### ISSUE TITLE
Regular S3 backups via webhook/cron job temporarily stall server.

### ISSUE THREAD

**Issue by jsunsawyer** [enupal/backup#20]
### Description
I have a cron job setup to backup our database to an Amazon S3 bucket via a webook.

As of about a week ago, our server has been stalling out as soon as the scheduled backup starts. The server resumes functioning as normal within a few minutes.

Our site currently has 24 sites set up for translation. DB backups are just over 40MB zipped.

Any idea what could be causing our issues?

I reached out on Discord and someone mentioned this:

> As far as I can see there are no console controllers for the plugin which is a little bit strange for such tasks. I bet the request times out.

### Additional info

- Craft version: 3.0.36
- PHP version: 7.1.27
- Database driver & version: MySQL 5.7.25
- Plugin version: 1.2.4

**Comment by andrelopez** [comment]
Hi @jsunsawter

Could you please recreate this issue and send back to us an email to support@enupal.com with a zip file of the next folder:

storage/logs

Also, could you please provide the next info about your server? What is the OS name and version?

**Comment by jsunsawyer** [comment]
@andrelopez Sent!

**Comment by andrelopez** [comment]
Hi @jsunsawyer feel free to reopen this ticket if you got the same issue again.
