### ISSUE TITLE
Cron job not working

### ISSUE THREAD

**Issue by migswd** [enupal/backup#21]
### Description
Hi. 
I am trying to do the cron job task to backup my website but it does not work.
I tested the link and it is working (I activated the cron job config).
https://myapp.com/enupal-backup/schedule?key=OLmCV46wS9

I got this line in my anacrontab : 
10 3 * * * wget https://myapp.com/enupal-backup/schedule?key=OLmCV46wS9 -O /dev/null

Where should I look to understand what is wrong ?
Is there any log in the plugin ? (I checked but did not see it)

### Additional info
PHP version | 7.3.0
Linux 4.9.124-paas-2270098
MySQL 5.7.23
Craft Pro 3.1.22
Enupal Backup 1.2.10

**Comment by andrelopez** [comment]
Hi @migswd 

Could you please test using Curl instead of Wget? e.g


`10   3   *  *  *  *    curl  --request GET 'https://myapp.com/enupal-backup/schedule?key=OLmCV46wS9'`

Please let us know how it goes

**Comment by migswd** [comment]
Hi. I tried it but it not work better.
Another idea ? :)

**Comment by andrelopez** [comment]
Hi @migswd 

Some hosting companies don’t allow access to cron, but there are websites offering alternative ways of scheduling jobs (free or paid-for). Here are some examples:

[SetCron](https://www.setcron.com/)
[SetCronJob](https://www.setcronjob.com/)
[OnlineCronJobs](http://www.onlinecronjobs.com/)
[EasyCron](https://www.easycron.com/)

**Comment by migswd** [comment]
Hi Andre.
It is working now. There was a special syntax to use on my hosting.
It works great thank you !!
