### ISSUE TITLE
Backup fails from inside control panel

### ISSUE THREAD

**Issue by bfjare** [enupal/backup#22]
### Description

I'm sure its a server issue but what is happening is the backup runs in two seconds and I get a couple of files with compressed sub-files inside of it. Remote destinations also don't work

### Steps to reproduce

1. Run Backup Pro from the control panel

### Additional info

- Craft version:  3.1.24
- PHP version: 7.3.3
- Database driver & version: 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1
- Plugin version: 1.2.11
CENTOS/RHEL7

**Comment by andrelopez** [comment]
Hi @bfjare 

Could you please recreate this issue and send back to us a zip file with the next folder:
`storage/logs`

Please send us an email to support@enupal.com

**Comment by bfjare** [comment]
Sending now.

**Comment by bfjare** [comment]
Confirming the fix was...  The server was missing the bzip2 library.  Thanks Andre.
