### ISSUE TITLE
Do not work on local dev (Mac / Mamp)

### ISSUE THREAD

**Issue by migswd** [enupal/backup#23]
### Description
It is working great on my online website but not locally on Mac / Mamp.

I can see the backup file has been generated (in the backup folder) and they are listed in Craft Enupal backups... but not size and when I click on them they is nothing : 
![image](https://user-images.githubusercontent.com/3531623/57133712-f5a77500-6da3-11e9-912c-27fab60f0195.png)
![image](https://user-images.githubusercontent.com/3531623/57133751-17a0f780-6da4-11e9-8ad8-69fbf08ae277.png)

Here is the error :

{"status":1,"timestamp":1556878177,"duration":0.27,"backupCount":11,"backupFailed":1,"errorCount":1,"errors":[{"class":"RuntimeException","message":"'mysqldump' was nowhere to be found please specify the correct path","file":"phar:\/\/\/Users\/migswd\/Workspace\/newmoowon\/www\/vendor\/enupal\/backup\/src\/resources\/phpbu.phar\/Util\/Cli.php","line":110}],"backups":[{"name":"Database","status":1,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Asset2","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Asset3","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Asset4","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Asset5","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Asset6","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Config1","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Config2","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Templates","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Web Folder","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}},{"name":"Logs","status":0,"checks":{"executed":0,"failed":0},"crypt":{"executed":0,"skipped":0,"failed":0},"syncs":{"executed":0,"skipped":0,"failed":0},"cleanup":{"executed":0,"skipped":0,"failed":0}}],"debug":["exception: 'mysqldump' was nowhere to be found please specify the correct path","\/usr\/bin\/tar --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/assets\/assets-general-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Applications\/MAMP\/htdocs\/newmoowon\/assets' 'general'","\/usr\/bin\/tar --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/assets\/assets-storiesImages-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Applications\/MAMP\/htdocs\/newmoowon\/assets' 'stories'","\/usr\/bin\/tar --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/assets\/assets-authorsImages-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Applications\/MAMP\/htdocs\/newmoowon\/assets' 'authors'","\/usr\/bin\/tar --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/assets\/assets-campaignsImages-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Applications\/MAMP\/htdocs\/newmoowon\/assets' 'campaigns'","\/usr\/bin\/tar --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/assets\/assets-usersImages-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Applications\/MAMP\/htdocs\/newmoowon\/assets' 'users'","\/usr\/bin\/tar --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/config\/config-configFolder-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Users\/migswd\/Workspace\/newmoowon\/www' 'config'","\/usr\/bin\/tar --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/config\/config-composerFile-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/runtime\/temp' 'enupal-backup-composer'","\/usr\/bin\/tar --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/templates\/templates-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Users\/migswd\/Workspace\/newmoowon\/www' 'templates'","\/usr\/bin\/tar --exclude='cpresources' --exclude='' --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/web\/web-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Applications\/MAMP\/htdocs' 'newmoowon'","\/usr\/bin\/tar --exclude='enupalbackup' --exclude='' --ignore-failed-read --force-local -cf '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage\/enupalbackup\/logs\/logs-new_moowon_20190503120937_ojyz2zm15w.tar' -C '\/Users\/migswd\/Workspace\/newmoowon\/www\/storage' 'logs'"]}

### Additional info

- Craft CMS 3.1.25
- PHP version: 7.1.22
- Database driver & version: MySQL 5.7.23
- Plugin version: 1.2.11
- OS : Darwin 18.0.0

**Comment by andrelopez** [comment]
Hi @migswd 

It looks like Enupal Backup can't find the `mysqldump` lib on your Mac. Are you able to run the next command from your terminal?

`mysqldump -V`

If not, could you please locate the `mysqldump` path on your machine and add it manually to the plugin on Enupal Backup -> Settings -> Paths

Enable Mysqldump and paste the path of the folder of the `mysqldump` lib. e.g `usr/bin/`

**Comment by andrelopez** [comment]
Hi @migswd I'll close this ticket, for now, feel free to reopen it if you want to follow up this issue.
