### ISSUE TITLE
Stalls/Freezes entire Craft admin panel, does not create backup

### ISSUE THREAD

**Issue by thisanimus** [enupal/backup#24]
### Description
After installing, and activating, I went to create my first backup.  I clicked backup and the loading spinner started spinning on the browser tab.  Nothing happened for about 5 minutes so I tried:
- Navigate away from admin/enupal-backup/backups. Did not ever load.
- Load the admin dashboard in another tab: Did not ever load.

I closed the browser and reopened it and was able to navigate around the admin panel. 
- Now whenever I try to access admin/enupal-backup/backups, it freezes the whole craft admin panel.  Same in Firefox, chrome, and safari.
- I can access admin/enupal-backup/settings without it crashing.

### Steps to reproduce

1. Install
2. Attempt to create backup

### Additional info

- Craft version: Craft Solo 3.1.25
- PHP version: 7.3.4
- Database driver & version: MySQL 5.5.5
- Plugin version: 1.2.12

**Comment by andrelopez** [comment]
Hi @thisanimus 

Sorry for the late reply. Could you please recreate this issue and send back to us a zip file of the next folders: `storage/logs` and `storage/enupalbackup` to support@enupal.com

**Comment by thisanimus** [comment]
Sorry.  Missed your replay.  Files on their way.

**Comment by timdov** [comment]
@thisanimus I was wondering if you were able to find the reason and solution for this issue? Any hint is much appreciated. Thanks.

**Comment by andrelopez** [comment]
Hi @timdov 

Could you please send back to us your `storage\logs` in a zip file to support@enupal.com ?

Best,

**Comment by timdov** [comment]
Hi @andrelopez 

I just sent it. 

Thanks

**Comment by andrelopez** [comment]
Feel free to reopen this issue if you still get this error.
