### ISSUE TITLE
Backup doesn't work.

### ISSUE THREAD

**Issue by shandy** [enupal/backup#27]
The backup doesn't work, I'm using the latest version of Craft (3.1.32.1). The backup is stuck on status 'running' and never completes. I've emailed support for help but they haven't resolved the issue, I can't recommend this plugin.

**Comment by andrelopez** [comment]
Hi Shandy,

I'm very sorry about this issue, for some reason we receive some support tickets in the spam folder. I just follow up your support email.

**Comment by stenrdj** [comment]
I've got the same issue here , the backup stuck at running status and never finished , any help could be provided to fix that please ?

**Comment by andrelopez** [comment]
@stenrdj Could you please recreate the issue and send back a zip file of the following folder: storage/logs? to support@enupal.com

**Comment by stenrdj** [comment]
> @stenrdj Could you please recreate the issue and send back a zip file of the following folder: storage/logs? to [support@enupal.com](mailto:support@enupal.com)

Thank you , email sent , can you please give it a look ? i really appreciate it !
