### ISSUE TITLE
Only backs up database

### ISSUE THREAD

**Issue by nitech** [enupal/backup#30]
When I run a backup, only the db is backed up. I expected templates, assets etc to also be backed up. 

Here's my settings: 

Database: Yes
Templates: Yes
Assets: Yes
Config Files: Yes
Web Root Directory: No

![image](https://user-images.githubusercontent.com/1279436/85284427-7ab18a00-b48f-11ea-93c5-740ca4eafb0d.png)

Running a trial version locally.

### Additional info

- Craft version: 3.4.24
- PHP version: 7.3.1
- Database driver & version:  5.7.24
- Plugin version: 1.1.3

**Comment by nitech** [comment]
On the server it backs up everything however.

**Comment by andrelopez** [comment]
Hi @nitech This could be an issue on the latest Craft CMS version, to start debugging, could you please send back to us a zip file of `storage/logs` folder to support@enupal.com?

**Comment by nitech** [comment]
Done. I had a peek at `storage/logs/enupalbackup` and it revealed: 

```json
"errors": [
    {
        "class": "phpbu\\App\\Backup\\Sync\\Exception",
        "message": "target file 'assets-bilder-secret-nasa-system_20200624021341_vivi1yekzl.tar' doesn't exist",
        "file": "phar://C:/secret-nasa-system/secret-nasa-system/vendor/enupal/backup/src/resources/phpbu.phar/Backup/Sync/AmazonS3v3.php",
        "line": 73
    },
    {
        "class": "phpbu\\App\\Backup\\Sync\\Exception",
        "message": "target file 'config-translations-secret-nasa-system_20200624021341_vivi1yekzl.tar' doesn't exist",
        "file": "phar://C:/secret-nasa-system/secret-nasa-system/vendor/enupal/backup/src/resources/phpbu.phar/Backup/Sync/AmazonS3v3.php",
        "line": 73
    },
    {
        "class": "phpbu\\App\\Backup\\Sync\\Exception",
        "message": "target file 'config-configFolder-secret-nasa-system_20200624021341_vivi1yekzl.tar' doesn't exist",
        "file": "phar://C:/secret-nasa-system/secret-nasa-system/vendor/enupal/backup/src/resources/phpbu.phar/Backup/Sync/AmazonS3v3.php",
        "line": 73
    },
    {
        "class": "phpbu\\App\\Backup\\Sync\\Exception",
        "message": "target file 'config-composerFile-secret-nasa-system_20200624021341_vivi1yekzl.tar' doesn't exist",
        "file": "phar://C:/secret-nasa-system/secret-nasa-system/vendor/enupal/backup/src/resources/phpbu.phar/Backup/Sync/AmazonS3v3.php",
        "line": 73
    },
    {
        "class": "phpbu\\App\\Backup\\Sync\\Exception",
        "message": "target file 'templates-secret-nasa-system_20200624021341_vivi1yekzl.tar' doesn't exist",
        "file": "phar://C:/secret-nasa-system/secret-nasa-system/vendor/enupal/backup/src/resources/phpbu.phar/Backup/Sync/AmazonS3v3.php",
        "line": 73
    }
],
```

also `/storage/enupalbackup/assets` did not contain any tar-file. The only folder there with contents was the `databases` folder. Note that I am running Craft on Windows through WAMP - and I've had some struggles with paths. I ended up having to enter the path for `mysqldump.exe` into the settings window: 

![image](https://user-images.githubusercontent.com/1279436/85528924-d0f80780-b60c-11ea-9f69-76b687c22ca1.png)

**Comment by andrelopez** [comment]
Glad to know that it is working on your server. On Windows, you may need to add the paths manually. Please follow [our docs] about how to add the paths on Windows.
Please let us know how it goes.

**Comment by nitech** [comment]
Hi @andrelopez, 

As of Windows 10 (build 17063) tar is included in Windows. 

By adding the following paths: 

![image](https://user-images.githubusercontent.com/1279436/85844263-bb1c4b00-b7a2-11ea-97c1-13384a8adb62.png)

I get the following log entries: 

```json
{
    "class": "phpbu\\App\\Backup\\Sync\\Exception",
    "message": "target file 'assets-bilder-amatec_automasjon_20200626024738_x3ag4lbny8.tar' doesn't exist",
    "file": "phar://C:/amatec/amatec_automasjon_craft_hyperlane/vendor/enupal/backup/src/resources/phpbu.phar/Backup/Sync/AmazonS3v3.php",
    "line": 73
}, ...
```

If I specify the filename of tar, like so `C:\windows\system32\tar.exe` I get an error in the log, saying; 

```json
{
    "class": "RuntimeException",
    "message": "wrong path specified for 'tar': C:\\Windows\\System32\\tar.exe",
    "file": "phar://C:/amatec/amatec_automasjon_craft_hyperlane/vendor/enupal/backup/src/resources/phpbu.phar/Util/Cli.php",
    "line": 126
}, ... 
```

## [cygwin works](https://cygwin.com/install.html)

I installed cygwin64 and changed the path to `c:\cygwin54\bin`, and now everything works. 

- Perhaps Enupal Backup should mark backup as failed or partially failed when it is able to backup and upload the database but not any of the other tasks? 
- Somehow the built in tar.exe doesn't do what Enupal Backup wants. Perhaps there is a difference in the accepted command line variables? Perhaps update your documentation with a line saying that the built in tar.exe in Windows is insufficient.


Note that the requirements for paths are a bit inconsistent.
