### ISSUE TITLE
Problems with allowAdminChanges

### ISSUE THREAD

**Issue by corneliusio** [enupal/backup#35]
### Description
This is somewhat two issues, but also closely related. The first issue is that in environments where `allowAdminChanges` is set to false, the plugin still allows you to adjust settings that would write to the project config files. The plugin also doesn't seem to respect these config files when they are pushed to the environment.

This also causes there to be no workaround on ephemeral filesystems where files cannot be updated. Configuration for the plugin can be set up locally, but the config does not get applied to the production server and cannot be updated without updating the database which is not really an option for production.

### Steps to reproduce
1. Setup plugin locally.
2. Configure backups in the plugin settings
3. Deploy updates to production
4. Settings remain in their default state.

### Additional info
- Craft version: 3.5.11.1
- PHP version: 7.4
- Database driver & version: MySQL 5.6
- Plugin version: 1.5

**Comment by NickLanger1990** [comment]
++

**Comment by andrelopez** [comment]
We just released Enupal Backup 2.1.0 with support to `allowAdminChanges`
