### ISSUE TITLE
Guide for setting up S3 Access

### ISSUE THREAD

**Issue by CreateSean** [enupal/backup#45]
Is there a guide for setting up S3 bucket access and bucket policy? 

Amazon makes it impossible to understand or figure out and I'm not sure what needs to be set up to work with Enupal backup

**Comment by andrelopez** [comment]
Hi @CreateSean 
Please feel free to follow the [aws docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/creating-bucket.html), you can leave default values.



<img width="929" alt="1" src="https://github.com/enupal/backup/assets/875476/2c8df124-a9c6-4b4f-b2cd-c672630540b4">

<img width="875" alt="2" src="https://github.com/enupal/backup/assets/875476/17b57c16-ccd8-499c-af99-1add174a41fa">

<img width="999" alt="3" src="https://github.com/enupal/backup/assets/875476/27230d89-be54-4592-90e8-262e1f2de066">

<img width="957" alt="4" src="https://github.com/enupal/backup/assets/875476/40172b6d-74c9-4d0b-ba33-ea2cfbeb40e6">

### Access keys
To get the **Key** and **Secret Key** you need to click on `Security Credentials` and then create the key on `Access keys `

<img width="438" alt="5" src="https://github.com/enupal/backup/assets/875476/bf35fe63-74b7-4d36-a3dc-5d2502c77a9c">


<img width="1343" alt="6" src="https://github.com/enupal/backup/assets/875476/c370f2fa-ed11-4a9d-9427-9717456f412a">

**Comment by CreateSean** [comment]
I'm connected and have ran a backup. 

I have assets enabled but in Amazon S3 I do **not** see the **assets** backup, though I do see database, config, config-translations, config-composer and logs.

Also in Craft I only see the database backups - is this normal?

![image](https://github.com/enupal/backup/assets/6899490/5e3396d3-10b0-451a-92cc-838f0be14059)

**Comment by andrelopez** [comment]
Hi @CreateSean, I was unable to recreate this issue. could you please recreate the issue and send back to us a zip file of the storage/logs folder to support@enupal.com ? 
Also could you please send us screenshots when you click on any of the backups and your settings under Enupal Backup -> Settings -> Backup files

**Comment by CreateSean** [comment]
Email sent

**Comment by CreateSean** [comment]
no response to emails in 2 days. Any update?

**Comment by andrelopez** [comment]
> no response to emails in 2 days. Any update?

Sorry, could you please double-check email was sent to support@enupal.com ? I can't see the email on inbox

**Comment by CreateSean** [comment]
confirmed sent to that email - also just now sent you a DM on discord with a dropbox link

**Comment by andrelopez** [comment]
We just released Enupal Backup 2.1.0 which fixes the assets not added on the backup and also the Backup ID link on the index page.
