### ISSUE TITLE
Project YAML and Production Environment allows changes still

### ISSUE THREAD

**Issue by CreateSean** [enupal/backup#46]
### Description
Settings are done locally and update project yaml files. I push those changes to production and apply. All good.

However I can still update the settings on production, this should be disabled as it is with Craft and other plugins
See screenshot from production site. If I update anything here, it will update project yaml files and mess up the git state of the server.

![image](https://github.com/enupal/backup/assets/6899490/78ded5e6-d49a-4c42-bd83-110edf0cf8c5)

Any settings that update yaml files should be disabled in production.

### Additional info

- Craft version: 4.4.16.1
- PHP version: 8.0
- Database driver & version:
- Plugin version: 2.0.0

**Comment by andrelopez** [comment]
Good catch! I am on it

**Comment by CreateSean** [comment]
no response to emails in 2 days. Any update?
