### ISSUE TITLE
Not backing up assets to Amazon S3

### ISSUE THREAD

**Issue by CreateSean** [enupal/backup#48]
### Description

Craft 4.4.16.1
Enupal Backups 2.1.0

I've got Enupal working so that it backups up everything. However when I check the S3 bucket the assets are not there, though I can see the database, logs, and config files in S3.

Also when I ran the backup I did not receive an email despite having added my email address and enabling  to the notifications option. The website does successfully send emails via the freeform plugin.

Please advise.

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 4.4.16.1
- PHP version:
- Database driver & version:
- Plugin version:  2.1.0

**Comment by andrelopez** [comment]
Hi @CreateSean are you able to see the assets on the CP when you click the Backup ID link on the Backups index page? if so what is the folder size? does the backup show as `completed` ?

**Comment by CreateSean** [comment]
@andrelopez Yes I can see it,, it's 6.05gb and is finished. See screenshot

![image](https://github.com/enupal/backup/assets/6899490/28eb543a-9716-4ac6-8963-2d362e97ef40)

**Comment by andrelopez** [comment]
@CreateSean could you please try enabling `MultiPartUpload` on Enupal Backup -> Settings -> Amazon S3` this settings could help on backups higher than 1gb

<img width="601" alt="Screenshot 2023-10-25 at 5 23 34 pm" src="https://github.com/enupal/backup/assets/875476/58e9c9a1-0a46-43ae-afb6-0893403d2c83">

**Comment by andrelopez** [comment]
@CreateSean The email functionality is working on my side, could you please make sure the `Sender Email Address` on `Enupal Backup -> Settings -> Notifications` is the same as your `System Email Address` on your Craft email settings?

**Comment by CreateSean** [comment]
@andrelopez multipartupload was already enabled.

changed email address and got notification on backup I just ran. However checking in Amazon see screenshot

![image](https://github.com/enupal/backup/assets/6899490/d4c9d181-1d09-4d44-9c1a-2a892f566ed2)

Also I'm setting up cron in Laravel forge with the command in red is it okay to change that to a full url with https?

![image](https://github.com/enupal/backup/assets/6899490/1de6a4fc-ac1b-4e2a-9b85-a089fe73ff28)

**Comment by andrelopez** [comment]
could you please send me a copy of your `storage/logs` folder to support@enupal.com? I found your old emails :)

**Comment by CreateSean** [comment]
Sent logs just now.

**Comment by andrelopez** [comment]
Hey @CreateSean We just released Enupal Backup v2.2.0 with a fix to this issue (also the issue of deleting multiple backups from the index page) please let me know how it goes

**Comment by andrelopez** [comment]
Issue fixed on Enupal Backup 2.2.0
