### ISSUE TITLE
Backup failing

### ISSUE THREAD

**Issue by damienbuckley** [enupal/backup#52]
### Description

Something has changed since last version. Now receiving this error:

02 - Could not create Enupal Backup: The shell command "cd /chroot/home/ae765bea/brownbros.co.nz/vendor/enupal/backup/src/resources && /opt/remi/php73/root/usr/bin/php phpbu.phar --configuration=/chroot/home/ae765bea/brownbros.co.nz/storage/enupalbackup/config.json --debug" failed with exit code 255: phpbu 6.0.20 by Sebastian Feldmann and contributors. Runtime: PHP 7.3.33 Configuration: /chroot/home/ae765bea/brownbros.co.nz/storage/enupalbackup/config.json backup: [mysqldump] ******************************************************* --Trace: #0 /chroot/home/ae765bea/brownbros.co.nz/vendor/enupal/backup/src/services/Backups.php(279): craft\errors\ShellCommandException::createFromCommand(Object(mikehaertl\shellcommand\Command)) #1 /chroot/home/ae765bea/brownbros.co.nz/vendor/enupal/backup/src/jobs/CreateBackup.php(51): enupal\backup\services\Backups->enupalBackup(Object(enupal\backup\elements\Backup)) #2 /chroot/home/ae765bea/brownbros.co.nz/vendor/yiisoft/yii2-queue/src/Queue.php(243): enupal\backup\jobs\CreateBackup->execute(Object(craft\queue\Queue)) #3 /chroot/home/ae765bea/brownbros.co.nz/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('99956', 'O:31:"enupal\\ba...', '300', 1) #4 /chroot/home/ae765bea/brownbros.co.nz/vendor/craftcms/cms/src/queue/Queue.php(131): yii\queue\cli\Queue->handleMessage('99956', 'O:31:"enupal\\ba...', '300', 1) #5 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure)) #6 /chroot/home/ae765bea/brownbros.co.nz/vendor/yiisoft/yii2-queue/src/cli/Queue.php(117): call_user_func(Object(Closure), Object(Closure)) #7 /chroot/home/ae765bea/brownbros.co.nz/vendor/craftcms/cms/src/queue/Queue.php(140): yii\queue\cli\Queue->runWorker(Object(Closure)) #8 /chroot/home/ae765bea/brownbros.co.nz/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run() #9 [internal function]: craft\controllers\QueueController->actionRun() #10 /chroot/home/ae765bea/brownbros.co.nz/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #11 /chroot/home/ae765bea/brownbros.co.nz/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array) #12 /chroot/home/ae765bea/brownbros.co.nz/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('run', Array) #13 /chroot/home/ae765bea/brownbros.co.nz/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('queue/run', Array) #14 /chroot/home/ae765bea/brownbros.co.nz/vendor/craftcms/cms/src/web/Application.php(608): craft\web\Application->runAction('queue/run', Array) #15 /chroot/home/ae765bea/brownbros.co.nz/vendor/craftcms/cms/src/web/Application.php(274): craft\web\Application->_processActionRequest(Object(craft\web\Request)) #16 /chroot/home/ae765bea/brownbros.co.nz/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request)) #17 /chroot/home/ae765bea/brownbros.co.nz/html/index.php(21): yii\base\Application->run() #18 {main}

### Steps to reproduce

1. Backup
2.

### Additional info

- Craft version: 3.9.6
- PHP version: 8.0.30
- Database driver & version: MariaDB 10.5.16
- Plugin version: 1.6.0

**Comment by andrelopez** [comment]
@damienbuckley could you please share your storage/logs folder? please send an email to support@enupal.com

Could you please rollback to prev version in the meantime?

**Comment by damienbuckley** [comment]
Hi. Logs sent. Working fine under v1.5.0

**Comment by damienbuckley** [comment]
Any progress on this? I have 6 sites using this plugin…

**Comment by damienbuckley** [comment]
For anyone else with the same problem - this is my fault - I had my PHP path set explicitly to PHP7.4.3 - which is obviously incompatible with newer versions of Enupal Backup. Once set to PHP8 this works fine. Apologies.
