### ISSUE TITLE
Error downloading database backup

### ISSUE THREAD

**Issue by umkasanki** [enupal/backup#8]
### Description
Error video: https://drive.google.com/file/d/1bWTL8xDd_MmQOTgYeRTUW2FMuxuJ7Loy/view?usp=sharing
Error screenshot:
![screen](https://user-images.githubusercontent.com/496132/46728880-8560c700-cc8c-11e8-92be-14b20700ecb3.png)

### Steps to reproduce

1. Go to the "Backups" section
2. Click the "Download all" button for any backup.

### Additional info

- Craft version: 3.0.25
- PHP version: 7.2.8
- Database driver & version: MySQL 5.7.22
- Plugin version:  1.1.8

**Comment by umkasanki** [comment]
Yes you are right.
The file has been deleted.
With the new backup, everything works fine.
Sorry to distract you. ;)

**Comment by andrelopez** [comment]
No problem 👍
